version: "3"

services:
  postgres-db:
    image: postgres:11.12
    container_name: postgres-db
    restart: on-failure
    tty: true
    environment:
      POSTGRES_DB: nodeauth
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - ./src/infra/.docker/postgres/dbdata:/var/lib/postgresql/data
    networks:
      - nodeauth

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@docker.com"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    volumes:
      - ./src/infra/.docker/postgres/pgadmin:/root
    networks:
      - nodeauth

  node-auth:
    build:
      context: ./
    container_name: node-auth
    tty: true
    entrypoint: sh ./src/infra/.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/node-auth/app
    networks:
      - nodeauth

networks:
  nodeauth:
    driver: bridge
